name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 3.1
          gemfile: Gemfile
          redis: latest
        - ruby: "3.0"
          gemfile: gemfiles/redis4.gemfile
        - ruby: 2.7
          gemfile: gemfiles/redis45.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - if: ${{ matrix.redis == 'latest' }}
      run: |
        curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list

    - run: |
        sudo apt-get update
        sudo apt-get install memcached redis-server
        sudo systemctl start memcached
        sudo systemctl start redis-server
    - run: bundle exec rake test
